title: 'Boudhayan'
description: "coding is fun."
baseurl: "/coding-fun"
url: "https://boudhayan.com"

header_pages:
  - index.md
  - questions.md
  - about.md
  - contact.md

style: dark

footer: 'follow me on <a href="https://medium.com/@iboudhayan">medium</a>, for more info, visit: <a href="https:boudhayan.com">boudhayan.com</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

google_analytics: UA-166030839-1
#listen_for_clients_preferred_style: true # true or false (default)

