title: 'Boudhayan'
description: "coding is fun."
baseurl: "/coding-fun"
url: "https://boudhayan.com"

header_pages:
  - index.md
  - questions.md
  - about.md
  - contact.md

style: dark

footer: 'follow me on <a href="https://medium.com/@iboudhayan">medium</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
